M48
; DRILL file {KiCad 7.0.10} date Mon Apr 28 11:59:38 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-28T11:59:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
%
G90
G05
T1
X133.0Y-63.0
X217.0Y-63.0
X217.0Y-97.0
T2
X134.115Y-81.0
T3
X142.335Y-97.0
X197.535Y-81.0
M30
